"""Shared kernel — lowest layer, zero dependencies beyond stdlib.

Ref: PLAN_02_CONVENTIONS_BASE_CONTRACTS.md.
"""

from ragbot.shared.clock import Clock, FrozenClock, SystemClock, get_clock
from ragbot.shared.errors import (
    ApplicationError,
    BusError,
    CacheError,
    CircuitBreakerOpen,
    CitationHallucinated,
    DomainError,
    ExternalServiceError,
    IdempotencyConflict,
    InfrastructureError,
    InvalidDocumentState,
    InvariantViolation,
    JobNotFound,
    LLMError,
    ModerationRejected,
    PolicyViolation,
    PromptInjectionDetected,
    QuotaExceeded,
    RagbotError,
    RepositoryError,
    TenantIsolationViolation,
    UseCaseError,
    VectorStoreError,
)
from ragbot.shared.result import ApiEnvelope, ErrorPayload, Err, Ok, Result
from ragbot.shared.types import (
    BotId,
    BotVersion,
    Channel,
    ChunkId,
    ConversationId,
    CorpusVersion,
    DocumentId,
    EmbeddingModelVersion,
    IdempotencyKey,
    JobId,
    JobStatus,
    MessageId,
    Role,
    TenantId,
    TraceId,
    UserId,
)

__all__ = [
    "ApiEnvelope",
    "ApplicationError",
    "BotId",
    "BotVersion",
    "BusError",
    "CacheError",
    "Channel",
    "ChunkId",
    "CircuitBreakerOpen",
    "CitationHallucinated",
    "Clock",
    "ConversationId",
    "CorpusVersion",
    "DocumentId",
    "DomainError",
    "EmbeddingModelVersion",
    "Err",
    "ErrorPayload",
    "ExternalServiceError",
    "FrozenClock",
    "IdempotencyConflict",
    "IdempotencyKey",
    "InfrastructureError",
    "InvalidDocumentState",
    "InvariantViolation",
    "JobId",
    "JobNotFound",
    "JobStatus",
    "LLMError",
    "MessageId",
    "ModerationRejected",
    "Ok",
    "PolicyViolation",
    "PromptInjectionDetected",
    "QuotaExceeded",
    "RagbotError",
    "RepositoryError",
    "Result",
    "Role",
    "SystemClock",
    "TenantId",
    "TenantIsolationViolation",
    "TraceId",
    "UseCaseError",
    "UserId",
    "VectorStoreError",
    "get_clock",
]
