from __future__ import annotations
from typing import Final  # noqa: F401
from ._08_sentry_otel import *  # noqa: F401,F403

# --- Message feedback (thumbs verdict loop) ---------------------------------
# Cap on free-text comment to prevent abusive payloads. Aggregation window
# default — caller may override per query.
MAX_FEEDBACK_COMMENT_LENGTH: Final[int] = 2000
DEFAULT_FEEDBACK_AGGREGATE_DAYS: Final[int] = 30
FEEDBACK_VERDICT_THUMBS_UP: Final[str] = "thumbs_up"
FEEDBACK_VERDICT_THUMBS_DOWN: Final[str] = "thumbs_down"

# --- Event subjects (Redis Streams) ------------------------------------------
SUBJECT_CHAT_RECEIVED: Final[str] = "chat.received.v1"
SUBJECT_CHAT_ANSWERED: Final[str] = "chat.answered.v1"
SUBJECT_CHAT_FAILED: Final[str] = "chat.failed.v1"
SUBJECT_CHAT_DELIVERY_FAILED: Final[str] = "chat.delivery_failed.v1"

SUBJECT_DOCUMENT_UPLOADED: Final[str] = "document.uploaded.v1"
SUBJECT_DOCUMENT_INGESTED: Final[str] = "document.ingested.v1"
SUBJECT_DOCUMENT_FAILED: Final[str] = "document.failed.v1"

SUBJECT_CORPUS_VERSION_CHANGED: Final[str] = "corpus.version_changed.v1"
SUBJECT_BOT_CONFIG_UPDATED: Final[str] = "bot.config_updated.v1"
SUBJECT_FEEDBACK_GIVEN: Final[str] = "feedback.given.v1"
SUBJECT_SECURITY_INCIDENT: Final[str] = "security.incident.v1"
SUBJECT_GUARDRAIL_RULES_CHANGED: Final[str] = "guardrail.rules_changed.v1"

# --- Guardrail rule loader (DB-driven moderation) ---------------------------
DEFAULT_GUARDRAIL_RULE_LOADER_TTL_S: Final[int] = 60

# --- Cache key prefixes -----------------------------------------------------
CACHE_KEY_SEMANTIC: Final[str] = "sc"
CACHE_KEY_RESPONSE: Final[str] = "resp"
CACHE_KEY_CHUNKS: Final[str] = "ret"
CACHE_KEY_EMBEDDING: Final[str] = "emb"
CACHE_KEY_IDEMPOTENCY: Final[str] = "idem"
CACHE_KEY_DEBOUNCE: Final[str] = "debounce"
CACHE_KEY_MODEL_RESOLVER: Final[str] = "ai_cfg"
CACHE_KEY_CIRCUIT_BREAKER: Final[str] = "cb"

# --- Superlative context enricher -------------------------------------------
DEFAULT_SUPERLATIVE_TOP_K: Final[int] = 5
DEFAULT_SUPERLATIVE_PARSER_TIMEOUT_MS: Final[int] = 50

# --- RAGAS-style automated eval harness -------------------------------------
DEFAULT_RAGAS_JUDGE_MODEL: Final[str] = "openai/gpt-4.1-mini"
DEFAULT_RAGAS_EMBED_MODEL: Final[str] = "openai/text-embedding-3-small"
DEFAULT_RAGAS_MAX_CONCURRENCY: Final[int] = 4
DEFAULT_RAGAS_REVERSE_QUESTIONS_N: Final[int] = 3

# --- Notify channel — webhook-driven error alerting -------------------------
# Resolution chain: system_config DB row → env JSON fallback → None.
# Cache window is short — admins editing the channel must see the new
# target on the next dispatch boundary, not stuck behind a long TTL.
DEFAULT_NOTIFY_CHANNEL_CACHE_TTL_S: Final[int] = 60
# HTTP timeout per webhook attempt; conservative because the whole point
# is to surface failures fast without holding the alert path hostage.
DEFAULT_NOTIFY_TIMEOUT_S: Final[float] = 5.0
# Application-level retry beyond circuit-breaker; only retries 5xx /
# timeout / network. 4xx (config wrong) drops immediately.
DEFAULT_NOTIFY_MAX_RETRIES: Final[int] = 2
# At most one in-flight POST per process — prevents an error storm from
# flooding the webhook target.
DEFAULT_NOTIFY_CONCURRENCY: Final[int] = 1
# Sliding-window cap; excess increments dropped_total{reason="rate_limit"}.
DEFAULT_NOTIFY_RATE_LIMIT_PER_MIN: Final[int] = 30
# Dedup window — same (severity, component, message-prefix) within this
# many seconds is collapsed to a single notification.
DEFAULT_NOTIFY_DEDUP_WINDOW_S: Final[int] = 60
# system_config row key holding the JSON ``NotifyChannelConfig`` body.
NOTIFY_CHANNEL_CONFIG_KEY: Final[str] = "notify_channel.config"
# Redis key prefixes — bucket suffix appended at dispatch time.
NOTIFY_REDIS_RATE_LIMIT_PREFIX: Final[str] = "ragbot:notify:ratelimit:"
NOTIFY_REDIS_DEDUP_PREFIX: Final[str] = "ragbot:notify:dedup:"
# Truncation length for the ``content`` string we POST upstream — keeps
# the alert readable in chat UI clients without flooding history.
NOTIFY_MESSAGE_TRUNCATE_CHARS: Final[int] = 1500

# --- Webhook HMAC secret rotation -------------------------------------------
# Window during which the PREVIOUS secret stays valid after a rotate, so a
# partner can roll their consumer without dropping signed deliveries. The
# verifier compares ``NOW()`` against ``revoked_at`` (set to ``now + grace``
# on the prior row at rotate-time); past that boundary the secret rejects.
DEFAULT_WEBHOOK_HMAC_GRACE_PERIOD_HOURS: Final[int] = 24
# HMAC primitive used for the X-Ragbot-Signature header — kept explicit so
# the algorithm choice is a single-line change at the constants layer.
DEFAULT_WEBHOOK_HMAC_ALGORITHM: Final[str] = "sha256"

# Observability label that groups LLM invocations by the high-level feature /
# subsystem that issued the call (e.g. "query.generation", "ingest.enrich",
# "router.classify"). Persisted to ``model_invocations.feature_name`` so cost
# audit can report ``feature_name | calls | tokens | cost_usd`` rollups. VARCHAR
# length matches the DB column.
FEATURE_NAME_MAX_LEN: Final[int] = 64
# Default sentinel when caller does not thread an explicit feature_name — kept
# short so the per-feature rollup separates legacy callers from instrumented
# ones at a glance.
DEFAULT_FEATURE_NAME_UNSET: Final[str] = "unset"

# Tenant-supplied slug that narrows scope below the tenant boundary. ASCII-safe
# so it flows through URL paths, Redis keys, and log labels untouched.
WORKSPACE_ID_MAX_LEN: Final[int] = 64
WORKSPACE_ID_MIN_LEN: Final[int] = 1
WORKSPACE_ID_PATTERN: Final[str] = r"^[a-zA-Z0-9-]+$"
WORKSPACE_ID_PATTERN_HUMAN: Final[str] = (
    "ASCII letters + digits + hyphen ('-') only — "
    "no spaces, no underscores, no accents, no special chars"
)
# ``tenant_uuid`` resolves a missing slug to ``str(record_tenant_id)``; a shared
# literal default across tenants would break isolation, so it is not offered.
DEFAULT_WORKSPACE_FALLBACK_MODE: Final[str] = "tenant_uuid"
# Slug used for tenant-level / forensic rows that do not belong to any
# workspace (audit_log, outbox, jobs, quotas, prompt_templates,
# prompt_versions, tenant_model_policy). The schema CHECK constraint
# accepts this literal alongside tenant-supplied slugs.
WORKSPACE_SYSTEM_SLUG: Final[str] = "system"

# Feedback-loop read path (ADR/P2-I W6-D12).
MAX_FEEDBACK_AGGREGATE_DAYS: Final[int] = 365
DEFAULT_FAQ_CANDIDATE_WINDOW_DAYS: Final[int] = 30
MAX_FAQ_CANDIDATE_WINDOW_DAYS: Final[int] = 365

# --- API schema version negotiation -----------------------------------------
# REST best practice: payload shape evolves via ``X-Schema-Version`` HTTP
# header, not URL prefix. URL stays purpose-named and stable; handlers branch
# on the lifted ``request.state.schema_version`` integer. Adding a new shape
# = extend the tuple and add the handler branch; no new router file, no URL
# break for existing B2B callers.
SCHEMA_VERSION_HEADER: Final[str] = "X-Schema-Version"
SUPPORTED_SCHEMA_VERSIONS: Final[tuple[int, ...]] = (1,)
DEFAULT_SCHEMA_VERSION: Final[int] = 1

# --- Stats Index — price bucket boundaries (document_service_index) ----------
# Deterministic Python parser uses these bucket thresholds for aggregate_summary().
# Values are VND integer amounts. Per zero-hardcode rule: parsers MUST import
# these constants instead of inlining the literals; bucket labels are computed
# at call-time from the tuple pairs so bucket names stay in sync with values.
# Override at runtime via system_config.price_buckets_vnd (JSON list of ints);
# the module-level tuple is the fallback when DB row is absent.
DEFAULT_PRICE_BUCKETS_VND: Final[tuple[int, ...]] = (
    500_000,    # "under_500k"
    1_000_000,  # "under_1M"
    2_000_000,  # "under_2M"
    5_000_000,  # "under_5M"
)
# Minimum amount considered a valid price (filters out ordinal numbers / codes
# that happen to match a numeric pattern). Values below this threshold are
# rejected by parse_money_vn so row-count integers (STT=1,2,3) stay out.
DEFAULT_PRICE_MIN_VND: Final[int] = 10_000

# --- Unified B2B ingest API (Phase 3 — case study 2026-05-16) ----------------
# Partner-facing ingest contract. Schema version is asserted both in the
# ``X-Schema-Version`` header (validated by ``SchemaVersionMiddleware``) and
# the request body's optional ``schema_version`` field; the accepted set
# below lets the ingest payload evolve on its own cadence independent of
# the platform-wide ``SUPPORTED_SCHEMA_VERSIONS``.
SUPPORTED_INGEST_SCHEMA_VERSIONS: Final[frozenset[int]] = frozenset({1})
# Max documents accepted in a single ``ingest_batch`` call. Cap exists so a
# misconfigured BE batch sync cannot blow per-tenant quota in one request,
# and so the per-batch quota check fits a single DB row-lock window.
DEFAULT_INGEST_BATCH_MAX: Final[int] = 100
# Mirrors ``documents.document_name`` + ``tool_name`` column lengths.
DEFAULT_INGEST_TITLE_MAX_LEN: Final[int] = 255
# ``X-Source-Tag`` header — opaque partner-side identifier (e.g. ``kms-a``,
# ``crm-b``, ``drive-sync``). Bound for audit + Phase 5 per-source RL.
DEFAULT_SOURCE_TAG_MAX_LEN: Final[int] = 64

_LEGACY_ALL = [
    "ANTHROPIC_PROVIDER_CODES",
    "AUDIT_MAX_TEMP_TABLES",
    "CACHE_KEY_CHUNKS",
    "CACHE_KEY_CIRCUIT_BREAKER",
    "CACHE_KEY_DEBOUNCE",
    "CACHE_KEY_EMBEDDING",
    "CACHE_KEY_IDEMPOTENCY",
    "CACHE_KEY_MODEL_RESOLVER",
    "CACHE_KEY_RESPONSE",
    "CACHE_KEY_SEMANTIC",
    "APP_ENV_DEVELOPMENT",
    "APP_ENV_PRODUCTION",
    "APP_ENV_STAGING",
    "APP_ENV_UAT",
    "APP_ENVS_STRICT",
    "BOT_ID_PATTERN",
    "CB_RESOURCE_DB",
    "CB_RESOURCE_LLM",
    "CHANNEL_TYPE_PATTERN",
    "DEFAULT_AUDIT_LIST_LIMIT",
    "DEFAULT_JWT_CLOCK_SKEW_S",
    "DEFAULT_LITELLM_DIRECT_ADAPTER_TIMEOUT_S",
    "DEFAULT_OUTBOX_POLL_LIMIT",
    "DEFAULT_OUTBOX_PUBLISH_BATCH_SIZE",
    "DEFAULT_RAGAS_FAITHFULNESS_GATE",
    "DEFAULT_RAGAS_MIN_ANSWER_RELEVANCY",
    "DEFAULT_RAGAS_MIN_CONTEXT_PRECISION",
    "DEFAULT_RAGAS_MIN_CONTEXT_RECALL",
    "DEFAULT_RAGAS_MIN_FAITHFULNESS",
    "DEFAULT_RAGAS_RELEVANCY_GATE",
    "DEFAULT_STEP_LATENCY_WINDOW_HOURS",
    "MAX_STEP_LATENCY_WINDOW_HOURS",
    "CB_RESOURCE_REDIS",
    "CIRCUIT_BREAKER_FAIL_MAX",
    "CIRCUIT_BREAKER_RESET_TIMEOUT",
    "DEFAULT_CIRCUIT_BREAKER_ENABLED",
    "DEBOUNCE_WINDOW_MS",
    "DEFAULT_CACHE_STAMPEDE_LOCK_TIMEOUT_S",
    "DEFAULT_SEMANTIC_CACHE_LOCK_TTL_S",
    "DEFAULT_SEMANTIC_CACHE_WAIT_RETRY_S",
    "DEFAULT_CB_COOLDOWN_S",
    "DEFAULT_CB_COOLDOWN_BASE_S",
    "DEFAULT_CB_COOLDOWN_STEP_S",
    "DEFAULT_CB_COOLDOWN_MAX_S",
    "DEFAULT_CB_FAILURE_THRESHOLD",
    "DEFAULT_CB_HALF_OPEN_MAX_CALLS",
    "DEFAULT_CB_POLICY_FAIL_MAX",
    "DEFAULT_CB_POLICY_RESET_TIMEOUT_S",
    "DEFAULT_CHAT_WORKER_CONCURRENCY",
    "DEFAULT_UVICORN_WORKERS",
    # Async chat queue (mega-sprint-G25 / G26)
    "CHAT_REQUEST_STREAM",
    "CHAT_REQUEST_CONSUMER_GROUP",
    "CHAT_RESULT_HASH_PREFIX",
    "DEFAULT_CHAT_RESULT_TTL_S",
    "DEFAULT_CHAT_STREAM_BLOCK_MS",
    "DEFAULT_CHAT_ERROR_TRUNCATE_CHARS",
    # Async callback delivery
    "DEFAULT_CALLBACK_TIMEOUT_S",
    "DEFAULT_CALLBACK_MAX_RETRIES",
    "DEFAULT_CALLBACK_BACKOFF_BASE_S",
    "DEFAULT_AUTHORITY_SCORE",
    "DEFAULT_AUTO_MERGE_MAX_PARENTS",
    "DEFAULT_AUTO_MERGE_RETRIEVAL_ENABLED",
    "DEFAULT_AUTO_MERGE_SIBLING_THRESHOLD",
    "DEFAULT_BLOCKS_API_ENABLED",
    "DEFAULT_BM25_NORMALIZATION_FLAGS",
    "DEFAULT_BM25_SUBSTRING_FALLBACK_ENABLED",
    "ACTION_CAPTURED_SLOTS_PLACEHOLDER",
    "DEFAULT_BM25_SYMBOL_PHRASE_ENABLED",
    "DEFAULT_METADATA_LAYER3_LLM_ENABLED",
    "DEFAULT_BOT_CONFIG_TTL_S",
    "DEFAULT_BOT_ID",
    "DEFAULT_CACHE_SIMILARITY_THRESHOLD",
    "DEFAULT_CHARS_PER_TOKEN_ESTIMATE",
    "DEFAULT_CHUNK_HASH_ID_ENABLED",
    "DEFAULT_CONTENT_TYPE_DISPATCH_ENABLED",
    "DEFAULT_MODALITY_BOOST_CODE_LOOKUP",
    "DEFAULT_MODALITY_BOOST_IDENTITY",
    "DEFAULT_MODALITY_BOOST_TABLE_LOOKUP",
    "DEFAULT_MODALITY_RERANK_ENABLED",
    "DEFAULT_NEIGHBOR_EXPAND_ENABLED",
    "DEFAULT_NEIGHBOR_MAX_CONCURRENCY",
    "DEFAULT_NEIGHBOR_TOKEN_BUDGET",
    "DEFAULT_NEIGHBOR_WINDOW_SIZE",
    "DEFAULT_ATOMIC_BLOCK_TYPES",
    "DEFAULT_ATOMIC_OVERSIZE_WARN_MULTIPLIER",
    "DEFAULT_CHUNK_FINGERPRINT_CHARS",
    "DEFAULT_CHUNK_MAX_SIZE",
    "DEFAULT_CHUNK_TYPE_CODE",
    "DEFAULT_CHUNK_TYPE_TABLE",
    "DEFAULT_CHUNK_TYPE_TABLE_ROW",
    "DEFAULT_CHUNK_TYPE_TEXT",
    "CHUNK_TYPES_ALLOWED",
    "DEFAULT_FORMULA_IMAGE_ATOMIC_PROTECT_ENABLED",
    "DEFAULT_TABLE_FOOTER_MAX_CHARS",
    "DEFAULT_TABLE_FOOTER_PRESERVE_ENABLED",
    "DEFAULT_XML_WRAP_ENABLED",
    "XML_WRAP_DEFAULT_ON_FROM_DATE",
    "DEFAULT_CHUNK_ORPHAN_THRESHOLD",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_OVERLAP_BOUNDARY",
    "DEFAULT_CHUNK_QUALITY_CORRUPTION_RATIO_MAX",
    "DEFAULT_CHUNK_QUALITY_INFO_DENSITY_FLOOR",
    "DEFAULT_CHUNK_QUALITY_INFO_DENSITY_TARGET",
    "DEFAULT_CHUNK_QUALITY_MAX_CHARS",
    "DEFAULT_CHUNK_QUALITY_MIN_CHARS",
    "DEFAULT_CHUNK_QUALITY_MIN_SCORE",
    "DEFAULT_CHUNK_QUALITY_OPTIMAL_CHARS",
    "DEFAULT_CHUNK_QUALITY_SCORER_PROVIDER",
    "DEFAULT_CHUNK_QUALITY_SCORING_ENABLED",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CLEANBASE_MAX_WORDS",
    "DEFAULT_CLEANBASE_MIN_WORDS",
    "DEFAULT_CLEANBASE_QUALITY_THRESHOLD",
    "DEFAULT_CONDENSE_HISTORY_LIMIT",
    "DEFAULT_CONNECT_ID",
    "DEFAULT_CONVO_SUMMARY_MAX_TOKENS",
    "DEFAULT_CONVO_SUMMARY_TRIGGER_TURNS",
    "DEFAULT_DEBUG_VIEW_FORMAT",
    "DEBUG_VIEW_FORMATS_ALLOWED",
    "DEFAULT_HYDE_ENABLED",
    "DEFAULT_HYDE_GENERATION_TIMEOUT_S",
    "DEFAULT_HYDE_MAX_TOKENS",
    "DEFAULT_HYDE_MODEL",
    "DEFAULT_HYDE_PROVIDER",
    "DEFAULT_HYDE_TEMPERATURE",
    "DEFAULT_DETERMINISTIC_TEMPERATURE",
    "DEFAULT_DETERMINISTIC_LLM_PURPOSES",
    "DEFAULT_CONTEXTUAL_RETRIEVAL_ENABLED",
    "DEFAULT_CONTEXT_BUFFER_ATOMIC_ENABLED",
    "DEFAULT_CONTEXT_BUFFER_SENTENCE_WINDOW",
    "DEFAULT_CONTEXT_TTL",
    "DEFAULT_CHUNK_CONTEXT_ENRICHMENT_CONCURRENCY",
    "DEFAULT_CHUNK_CONTEXT_MAX_TOKENS",
    "DEFAULT_CR_CONTEXT_MAX_TOKENS",
    "DEFAULT_CR_ENHANCED_ENABLED",
    "DEFAULT_CR_MAX_DOC_CHARS",
    "DEFAULT_CR_PROMPT_CACHE_ENABLED",
    "DEFAULT_EF_SEARCH",
    "DEFAULT_CONTENT_HASH_HEX_LEN",
    "DEFAULT_DIFF_REINGEST_ENABLED",
    "DEFAULT_EMBED_COST_USD_PER_1M_TOKENS",
    "DEFAULT_CHARS_PER_TOKEN_ESTIMATE",
    "TOKENS_PER_MILLION",
    "DEFAULT_VECTOR_STORE_PROVIDER",
    "DEFAULT_VOCAB_FACTORY_CACHE_SIZE",
    "DEFAULT_EMBEDDING_DIM",
    "DEFAULT_EMBEDDING_PASSAGE_PREFIX",
    "DEFAULT_EMBEDDING_TEXT_STRATEGY",
    "EMBEDDING_TEXT_STRATEGY_AUTO",
    "STRUCTURAL_CHUNK_STRATEGIES",
    "DEFAULT_HYBRID_RRF_BM25_WEIGHT",
    "DEFAULT_HYBRID_RRF_VECTOR_WEIGHT",
    "DEFAULT_ADAPTIVE_RERANK_WEIGHT_ENABLED",
    "DEFAULT_RERANK_WEIGHTS_BY_INTENT",
    "DEFAULT_STRUCTURED_REF_EXTRACTION_ENABLED",
    "DEFAULT_METADATA_FILTER_PROVIDER",
    "DEFAULT_METADATA_EXTRACT_MAX_TOKENS",
    "DEFAULT_METADATA_EXTRACT_TIMEOUT_S",
    "DEFAULT_METADATA_CACHE_TTL_S",
    "DEFAULT_METADATA_INGEST_CONCURRENCY",
    "DEFAULT_METADATA_EXTRACTION_FALLBACK_MODEL",
    "METADATA_SCHEMA_KEYS",
    "METADATA_INTENT_ENUM",
    "DEFAULT_ARTICLE_REF_PATTERNS",
    "CHUNK_LEVEL_METADATA_FILTER_KEYS",
    "DEFAULT_EMBED_CACHE_TTL",
    "DEFAULT_UNDERSTAND_QUERY_CACHE_TTL_S",
    "DEFAULT_EMBED_CACHE_TTL_S",
    "PROMPT_VERSION_UQ",
    "DEFAULT_EVAL_RELEVANCE_THRESHOLD",
    "DEFAULT_CITATIONS_TOP_K",
    "DEFAULT_EVAL_TOP_K",
    "DEFAULT_FEEDBACK_AGGREGATE_DAYS",
    "DEFAULT_FRESHNESS_HALF_LIFE_DAYS",
    "DEFAULT_LANGUAGE",
    "VI_DOMAIN_LANGUAGES",
    "SUPERLATIVE_SUPPORTED_LANGUAGES",
    "SYSTEM_CONFIG_KEY_DEFAULT_VOCAB_VI",
    "LANGUAGE_PACK_CACHE_PREFIX",
    "LANGUAGE_PACK_PROMPT_KEYS",
    "MULTI_QUERY_INTENT_PROMPT_KEYS",
    "DEFAULT_MULTI_QUERY_PROMPT_KEY",
    "DEFAULT_GROUNDING_CHECK_THRESHOLD",
    "DEFAULT_GROUNDING_INTENTS",
    "DEFAULT_GROUNDING_CHECK_ASYNC_ENABLED",
    "DEFAULT_GROUNDING_CHECK_ASYNC_TOP_SCORE_THRESHOLD",
    "DEFAULT_GROUNDING_CHECK_ASYNC_INTENTS",
    "DEFAULT_ABLATION_KEEP_COST_DROP_PCT",
    "DEFAULT_ABLATION_KEEP_LATENCY_DROP_PCT",
    "DEFAULT_ABLATION_KEEP_PASS_LIFT_PP",
    "DEFAULT_GENERATE_P95_SLA_MS",
    "DEFAULT_GUARDRAIL_LEAK_SHINGLE_SIZE",
    "DEFAULT_GUARDRAIL_OOS_SIMILARITY_THRESHOLD",
    "DEFAULT_CRAG_BATCH_GRADER_MAX_CHUNKS",
    "DEFAULT_CRAG_GRADER_PROVIDER",
    "DEFAULT_CRAG_GRADE_CONCURRENCY",
    "DEFAULT_CRAG_LENIENT_GRADE_FOR_COMPOUND_INTENTS_ENABLED",
    "DEFAULT_CRAG_LENIENT_GRADE_INTENTS",
    "DEFAULT_GENERATE_HISTORY_MAX_MSGS",
    "DEFAULT_GENERATE_MAX_TOKENS_BY_INTENT",
    "DEFAULT_HISTORY_LIMIT",
    "DEFAULT_DEDUP_JACCARD_THRESHOLD",
    "DEFAULT_DEDUP_MIN_CHARS",
    "DEFAULT_CORPUS_CLEAN_EXCERPT_CHARS",
    "DEFAULT_CORPUS_CLEAN_SERVICE_MIN_CHARS",
    "DEFAULT_CORPUS_CLEAN_PRICE_REGEX",
    "DEFAULT_CORPUS_CLEAN_RAG_FRIENDLY_MIN_WORDS",
    "DEFAULT_CORPUS_CLEAN_RAG_FRIENDLY_MAX_WORDS",
    "DEFAULT_DEV_TOKEN_ALLOW_NETWORK",
    "DEFAULT_DEV_TOKEN_ENABLED",
    "DEFAULT_DEV_TOKEN_SELF_TTL_REDIS_S",
    "DEFAULT_IDEMPOTENCY_TTL",
    "DEFAULT_INGEST_BATCH_MAX",
    "DEFAULT_INGEST_TITLE_MAX_LEN",
    "DEFAULT_JWT_TTL_S",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_ZEROENTROPY_API_URL",
    "DEFAULT_ZEROENTROPY_EMBEDDING_DIM",
    "DEFAULT_ZEROENTROPY_EMBEDDING_MODEL",
    "DEFAULT_BKAI_VN_EMBEDDING_MODEL",
    "DEFAULT_BKAI_VN_EMBEDDING_DIM",
    "DEFAULT_BKAI_VN_EMBEDDING_ENDPOINT_PATH",
    "DEFAULT_JINA_EMBEDDING_MODEL",
    "DEFAULT_EMBEDDING_TASK_QUERY",
    "DEFAULT_EMBEDDING_TASK_PASSAGE",
    "DEFAULT_EMBEDDING_COLUMN",
    "ALLOWED_EMBEDDING_COLUMNS",
    "JINA_EMBEDDING_MODEL_PREFIXES",
    # Embedder failover + BM25 fallback
    "DEFAULT_EMBEDDING_PROVIDER",
    "DEFAULT_EMBEDDING_SECONDARY_PROVIDER",
    "DEFAULT_EMBEDDING_FAILOVER_ENABLED",
    "DEFAULT_RETRIEVAL_BM25_FALLBACK_ENABLED",
    "DEFAULT_RETRIEVAL_BM25_FALLBACK_TOP_K",
    "DEFAULT_RETRIEVAL_MULTISTAGE_ENABLED",
    "DEFAULT_RETRIEVAL_EARLY_EXIT_THRESHOLD",
    "DEFAULT_RETRIEVAL_STAGES",
    "DEFAULT_RETRIEVAL_BM25_STAGE_TOP_K_MULTIPLIER",
    "DEFAULT_RETRIEVAL_KEYWORD_STAGE_PATTERN",
    "DEFAULT_RETRIEVAL_KEYWORD_STAGE_SCORE",
    "DEFAULT_OPENAI_EMBEDDING_MODEL",
    "DEFAULT_OPENAI_EMBEDDING_DIMENSION",
    "DEFAULT_EMBEDDER_HEALTHCHECK_TIMEOUT_S",
    # Multi-vector embedding scaffold (Phase-C late-interaction prep)
    "DEFAULT_MULTI_VECTOR_ENABLED",
    "DEFAULT_MULTI_VECTOR_PROVIDER",
    "DEFAULT_MULTI_VECTOR_MAX_SENTENCES",
    "DEFAULT_MULTI_VECTOR_MIN_SENTENCE_CHARS",
    "DEFAULT_MAX_HISTORY",
    "DEFAULT_MAX_TOKENS_TOTAL",
    "DEFAULT_ENTITY_EXTRACTOR_PROVIDER",
    "DEFAULT_ENTITY_GROUNDING_ENABLED",
    "DEFAULT_ENTITY_GROUNDING_MAX_ENTITIES",
    "DEFAULT_INTENT_CONFIDENCE_FALLBACK",
    "DEFAULT_INTENT_EXTRACTOR_MAX_TOKENS",
    "DEFAULT_INTENT_EXTRACTOR_QUERY_PREVIEW_CHARS",
    "DEFAULT_DECOMPOSE_CONFIDENCE_GATE",
    "DEFAULT_QUERY_COMPLEXITY_WEIGHT_COMMA",
    "DEFAULT_QUERY_COMPLEXITY_WEIGHT_CONJUNCTION",
    "DEFAULT_QUERY_COMPLEXITY_WEIGHT_NUMBERS",
    "DEFAULT_QUERY_COMPLEXITY_WEIGHT_QUESTION",
    "DEFAULT_QUERY_COMPLEXITY_LENGTH_NORMALIZER",
    "DEFAULT_QUERY_COMPLEXITY_THRESHOLD",
    "DEFAULT_QUERY_COMPLEXITY_STRUCTURAL_REF_PATTERN",
    "DEFAULT_QUERY_COMPLEXITY_STRUCTURAL_MAX_CHARS",
    "DEFAULT_QUERY_COMPLEXITY_CONJUNCTIONS_JSON",
    "DEFAULT_DECOMPOSER_ENABLED",
    "DEFAULT_DECOMPOSER_MODEL",
    "DEFAULT_DECOMPOSER_MAX_TOKENS",
    "DEFAULT_DECOMPOSER_MAX_SUB_QUERIES",
    "DEFAULT_ADAPTIVE_ROUTER_L1_ENABLED",
    "DEFAULT_MQ_VARIANT_SIMILARITY_DEDUP_THRESHOLD",
    "DEFAULT_MQ_ENTITY_CONFIDENCE_GATE",
    "DEFAULT_INVOCATION_STUCK_TIMEOUT_S",
    "DEFAULT_METADATA_AWARE_RETRIEVAL_ENABLED",
    "DEFAULT_METADATA_EXTRACTION_MODEL",
    "DEFAULT_METADATA_FALLBACK_RELAX_ENABLED",
    "DEFAULT_MAX_REFLECT_RETRIES",
    "DEFAULT_CRAG_SKIP_RETRY_ABOVE_SCORE",
    "DEFAULT_GRADE_TIMEOUT_S",
    "DEFAULT_INGEST_IDEMPOTENCY_TTL_HOURS",
    "INGEST_IDEMPOTENCY_HEADER",
    "INGEST_IDEMPOTENCY_KEY_MAX_LEN",
    "INGEST_IDEMPOTENCY_STATE_DONE",
    "INGEST_IDEMPOTENCY_STATE_FAILED",
    "INGEST_IDEMPOTENCY_STATE_PROCESSING",
    "DEFAULT_REFLECT_SKIP_IF_GROUNDED",
    "DEFAULT_REFLECT_SKIP_TOP_SCORE_FLOOR",
    "DEFAULT_REFLECTION_ENABLED",
    "DEFAULT_MMR_LAMBDA",
    "DEFAULT_MMR_SIMILARITY_THRESHOLD",
    "DEFAULT_ABBREVIATIONS_CACHE_TTL_S",
    "DEFAULT_MODEL_RESOLVER_CACHE_TTL",
    "DEFAULT_MODEL_RESOLVER_L1_MAX_SIZE",
    "DEFAULT_MODEL_RESOLVER_L1_TTL_S",
    "DEFAULT_MODEL_RESOLVER_L2_TTL_S",
    "DEFAULT_DYNAMIC_ROUTER_REFRESH_INTERVAL_S",
    "DEFAULT_REDIS_HEALTH_CHECK_INTERVAL_S",
    "DEFAULT_REDIS_SOCKET_TIMEOUT_S",
    "DEFAULT_REDIS_SOCKET_CONNECT_TIMEOUT_S",
    "DEFAULT_REDIS_STREAMS_SOCKET_TIMEOUT_S",
    "DEFAULT_REDIS_STREAMS_SOCKET_CONNECT_TIMEOUT_S",
    "DEFAULT_REDIS_STREAMS_MAX_CONNECTIONS",
    "DEFAULT_BUS_HANDLER_CONCURRENCY",
    "DEFAULT_DB_POOL_SIZE",
    "DEFAULT_DB_MAX_OVERFLOW",
    "DEFAULT_DB_POOL_RECYCLE_S",
    "DEFAULT_DB_POOL_TIMEOUT_S",
    "DEFAULT_REDIS_POOL_SIZE",
    "DEFAULT_EMBEDDING_FALLBACK_MODEL",
    "DEFAULT_EMBEDDING_FALLBACK_DIMENSION",
    "DEFAULT_EMBEDDING_FALLBACK_VERSION",
    "DEFAULT_CHUNKING_HEADING_THRESHOLD",
    "DEFAULT_CHUNKING_AVG_LEN_SHORT",
    "DEFAULT_CHUNKING_TABLE_THRESHOLD",
    "DEFAULT_CHUNKING_AVG_LEN_LONG",
    "DEFAULT_CHUNKING_HEADING_MAX_FOR_SEMANTIC",
    "DEFAULT_CHUNKING_MIXED_CONTENT_THRESHOLD",
    "DEFAULT_ENRICHMENT_MODEL",
    "DEFAULT_ENRICHMENT_TEMPERATURE",
    "DEFAULT_ENRICHMENT_MAX_TOKENS",
    "DEFAULT_ENRICHMENT_TIMEOUT_S",
    "DEFAULT_JWT_ALGORITHM",
    "DEFAULT_JWT_ISSUER",
    "DEFAULT_JWT_AUDIENCE",
    "DEFAULT_RAG_TOP_K",
    "DEFAULT_RAG_RERANK_TOP_N",
    "DEFAULT_SEMANTIC_CACHE_HIT_LOG_ENABLED",
    "DEFAULT_SEMANTIC_CACHE_THRESHOLD",
    "DEFAULT_MAX_ITERATION_CAP",
    "DEFAULT_DEBOUNCE_WINDOW_MS",
    "DEFAULT_CIRCUIT_BREAKER_FAIL_MAX",
    "DEFAULT_CIRCUIT_BREAKER_RESET_TIMEOUT_S",
    "DEFAULT_APP_PORT",
    "DEFAULT_PARSER_HTTP_TIMEOUT_S",
    "DEFAULT_PARSED_MD_DIR",
    "DEFAULT_PARSED_MD_SUFFIX",
    "DEFAULT_PARSED_MD_RETENTION_DAYS",
    "DEFAULT_SPEC_LLM_TEMPERATURE",
    "DEFAULT_SPEC_LLM_MAX_TOKENS",
    "DEFAULT_SPEC_LLM_TOP_P",
    "DEFAULT_SPEC_RERANK_TOP_N",
    "DEFAULT_SPEC_RERANK_BATCH_SIZE",
    "DEFAULT_SPEC_EMBEDDING_MAX_BATCH",
    "DEFAULT_P95_SLA_SECONDS",
    "DEFAULT_P99_SLA_SECONDS",
    "DEFAULT_P99_OUTLIER_THRESHOLD_S",
    "DEFAULT_SLA_P95_WARN_SECONDS",
    "DEFAULT_SLA_P95_CRITICAL_SECONDS",
    "DEFAULT_SLA_ERROR_RATE_WARN",
    "DEFAULT_SLA_ERROR_RATE_CRITICAL",
    "DEFAULT_SLA_CACHE_HIT_RATIO_WARN",
    "DEFAULT_SLA_CIRCUIT_OPEN_DURATION_S",
    "DEFAULT_SLA_BREACH_WINDOW_S",
    "DEFAULT_WARMUP_ENABLED",
    "DEFAULT_WARMUP_TIMEOUT_S",
    "DEFAULT_WARMUP_LLM_PROBE_TEXT",
    "DEFAULT_WARMUP_LLM_MAX_TOKENS",
    "DEFAULT_HEALTH_MODELS_DEGRADED_LATENCY_MS",
    "DEFAULT_HEALTH_MODELS_PROBE_TIMEOUT_S",
    "DEFAULT_HTTP_CLIENT_PROBE_TIMEOUT_S",
    "DEFAULT_DB_BOOTSTRAP_CONNECT_TIMEOUT_S",
    "DEFAULT_HEALTH_PROBE_DOC_A",
    "DEFAULT_HEALTH_PROBE_DOC_B",
    "DEFAULT_HEALTH_PROBE_LLM_MAX_TOKENS",
    "DEFAULT_HEALTH_PROBE_LLM_PROMPT",
    "DEFAULT_HEALTH_PROBE_QUERY",
    "DEFAULT_JINA_HEALTH_CHECK_TIMEOUT_S",
    "DEFAULT_API_KEY_COOLDOWN_S",
    "API_KEY_COOLDOWN_REDIS_PREFIX",
    "API_KEY_FAILOVER_ENABLED",
    "MS_PER_SECOND",
    "DEFAULT_JINA_RERANKER_CB_FAIL_MAX",
    "DEFAULT_JINA_RERANKER_CB_RESET_S",
    "DEFAULT_JINA_RERANKER_MAX_ATTEMPTS",
    "DEFAULT_JINA_RERANKER_MAX_DOCS",
    "DEFAULT_JINA_RERANKER_MODEL",
    "DEFAULT_JINA_RERANKER_SCORE_PRECISION",
    "DEFAULT_JINA_RERANKER_TIMEOUT_S",
    "DEFAULT_RERANK_INTENT_WHITELIST_ENABLED",
    "DEFAULT_RERANK_SKIP_INTENTS",
    "DEFAULT_RERANK_MODEL",
    "DEFAULT_RERANK_TOP_N",
    "DEFAULT_RERANK_WHITELIST_INTENTS",
    "DEFAULT_RETRIEVE_SMOKE_MIN_CHUNKS",
    "DEFAULT_RETRIEVE_SMOKE_MIN_COSINE",
    "DEFAULT_ROBUST_JSON_PARSER_ENABLED",
    "DEFAULT_ROBUST_JSON_PARSE_PREVIEW_CHARS",
    "ROBUST_JSON_PARSER_FLAG_KEY",
    "DEFAULT_RRF_K",
    "DEFAULT_SEMANTIC_CACHE_TTL",
    "_REFUSE_ANSWER_TYPES",
    "DEFAULT_OOS_ANSWER_TEMPLATE",
    "DEFAULT_PARTIAL_GROUND_THRESHOLD",
    "SYSPROMPT_VERSION_BASELINE",
    "SYSPROMPT_VERSION_CONTEXT_AWARE",
    "DEFAULT_SYSPROMPT_VERSION",
    "ALLOWED_SYSPROMPT_VERSIONS",
    "DEFAULT_REFUSE_SHORT_CIRCUIT_ENABLED",
    "DEFAULT_CHITCHAT_QUERY_MAX_TOKENS",
    "DEFAULT_HALLU_TRAP_KEYWORDS",
    "DEFAULT_TOP_K",
    "DEFAULT_RETRIEVE_TOP_K_BY_INTENT",
    "DEFAULT_VI_COMPOUND_SEGMENTATION_INGEST_ENABLED",
    "DEFAULT_VI_COMPOUND_SEGMENTATION_THROUGHPUT_CHARS_PER_S",
    "DEFAULT_VI_COMPOUND_SEGMENTATION_TIMEOUT_S",
    "DEFAULT_VN_FILLER_TOKENS_JSON",
    "DEFAULT_TENANT_ALLOWED_ORIGINS",
    "DEFAULT_TENANT_BYPASS_RATE_LIMIT",
    "DEFAULT_TENANT_CONFIG_TTL_S",
    "DEFAULT_TENANT_RATE_LIMIT_PER_MIN",
    "DEFAULT_TENANT_RATE_LIMIT_WINDOW_S",
    "DEFAULT_TENANT_TOKEN_CAP_BLOCK_PERCENT",
    "DEFAULT_TENANT_TOKEN_CAP_ENFORCE_PREFLIGHT",
    "DEFAULT_TENANT_TOKEN_CAP_WARN_PERCENT",
    "DEFAULT_RL_ADMIN_PER_MIN",
    "DEFAULT_RL_BURST_FACTOR",
    "DEFAULT_RL_BURST_WINDOW_S",
    "DEFAULT_RL_CHAT_PER_MIN",
    "DEFAULT_RL_BOT_PER_MIN",
    "DEFAULT_RL_UPLOAD_PER_MIN",
    "DEFAULT_UPLOAD_STREAM_MAX_BYTES",
    "DEFAULT_UPLOAD_STREAM_CHUNK_SIZE",
    "DEFAULT_UPLOAD_TEMP_DIR",
    "SUBJECT_DOCUMENT_UPLOAD_STREAM",
    "DEFAULT_DOCUMENTS_PER_DAY_LIMIT",
    "DEFAULT_RL_DEFAULT_PER_MIN",
    "DEFAULT_RL_EMIT_HEADERS",
    "DEFAULT_RL_FAIL_MODE",
    "DEFAULT_RL_SYNC_PER_MIN",
    "DEFAULT_RL_WINDOW_S",
    "DEFAULT_SOURCE_RL_PER_MIN",
    "DEFAULT_SOURCE_RL_WINDOW_S",
    "DEFAULT_SOURCE_TAG_MAX_LEN",
    "SOURCE_RL_INGEST_PATH_SUFFIX",
    "SOURCE_RL_TAG_MAX_LEN",
    "DEFAULT_CORS_ALLOW_HEADERS",
    "DEFAULT_CORS_ALLOW_METHODS",
    "DEFAULT_CORS_PREFLIGHT_MAX_AGE_S",
    "FALLBACK_RATE_LIMIT_VALUE",
    "FALLBACK_RATE_LIMIT_WINDOW",
    "FEEDBACK_VERDICT_THUMBS_DOWN",
    "FEEDBACK_VERDICT_THUMBS_UP",
    "MAX_CHAT_CONTENT_LENGTH",
    "MAX_CONTENT_LENGTH",
    "MAX_DOCUMENT_CONTENT_CHARS",
    "MAX_DOCUMENT_NAME_LENGTH",
    "MAX_DOWNLOAD_BYTES",
    "MAX_EF_SEARCH",
    "MAX_FEEDBACK_COMMENT_LENGTH",
    "MAX_FILE_SIZE_BYTES",
    "MAX_HISTORY_LIMIT_REQUEST",
    "MAX_HISTORY_MESSAGE_CHARS",
    "MAX_ITERATION_CAP",
    "MAX_TOKENS_PER_REQUEST",
    "OPENAI_AUTO_CACHE_MIN_TOKENS",
    "QUALITY_WEIGHT_INFO_DENSITY",
    "QUALITY_WEIGHT_LANGUAGE",
    "QUALITY_WEIGHT_NO_CORRUPTION",
    "QUALITY_WEIGHT_TEXT_LENGTH",
    "ROLLING_SUMMARY_THRESHOLD",
    "ROLLING_SUMMARY_KEEP_LAST",
    "RRF_K",
    "SEMANTIC_CACHE_THRESHOLD",
    "SUBJECT_BOT_CONFIG_UPDATED",
    "SUBJECT_CHAT_ANSWERED",
    "SUBJECT_CHAT_DELIVERY_FAILED",
    "SUBJECT_CHAT_FAILED",
    "SUBJECT_CHAT_RECEIVED",
    "SUBJECT_CORPUS_VERSION_CHANGED",
    "SUBJECT_DOCUMENT_FAILED",
    "SUBJECT_DOCUMENT_INGESTED",
    "SUBJECT_DOCUMENT_UPLOADED",
    "SUBJECT_FEEDBACK_GIVEN",
    "SUBJECT_GUARDRAIL_RULES_CHANGED",
    "SUBJECT_SECURITY_INCIDENT",
    "SCHEMA_VERSION_HEADER",
    "SUPPORTED_SCHEMA_VERSIONS",
    "DEFAULT_SCHEMA_VERSION",
    "SUPPORTED_INGEST_SCHEMA_VERSIONS",
    "DEFAULT_GUARDRAIL_RULE_LOADER_TTL_S",
    "SUBJECT_SYSTEM_CONFIG_CHANGED",
    "SUBJECT_TOKEN_REVOKED",
    "DEFAULT_OUTBOX_DEDUP_TTL_S",
    "DEFAULT_SUPERLATIVE_TOP_K",
    "DEFAULT_SUPERLATIVE_PARSER_TIMEOUT_MS",
    "DEFAULT_GENERIC_VOCAB_ENABLED",
    "DEFAULT_GENERIC_VOCAB_MAX_MATCHES_PER_QUERY",
    "DEFAULT_GENERIC_VOCAB_MAX_EXPANSIONS_PER_MATCH",
    "DEFAULT_VOCAB_NGRAM_MAX_N",
    "DEFAULT_VOCAB_NEGATION_LOOKBACK_TOKENS",
    "DEFAULT_VN_NEGATION_TOKENS",
    "VN_HONORIFIC_LABELS",
    "DEFAULT_RAGAS_JUDGE_MODEL",
    "DEFAULT_RAGAS_EMBED_MODEL",
    "DEFAULT_RAGAS_MAX_CONCURRENCY",
    "DEFAULT_RAGAS_REVERSE_QUESTIONS_N",
    "DEFAULT_LOADTEST_REFUSE_PATTERNS",
    "DEFAULT_LOADTEST_REQUEST_TIMEOUT_S",
    "DEFAULT_LOADTEST_RATE_LIMIT_RETRY_SLEEP_S",
    "DEFAULT_LOADTEST_MAX_TOKEN_REFRESH_RETRIES",
    "DEFAULT_LOADTEST_INTER_ROOM_SLEEP_S",
    "DEFAULT_LOADTEST_INTER_QUESTION_SLEEP_S",
    "DEFAULT_LOADTEST_MIN_PASS_ANSWER_CHARS",
    "DEFAULT_LOADTEST_ANSWER_TRUNCATE_CHARS",
    "DEFAULT_LOADTEST_FACTUAL_LEN_THRESHOLD",
    "DEFAULT_FAQ_MIN_OCCURRENCES",
    "DEFAULT_FAQ_CLUSTER_SIMILARITY",
    "DEFAULT_PROMPT_COMPRESSION_ENABLED",
    "DEFAULT_PROMPT_COMPRESSION_MAX_CHARS_PER_CHUNK",
    "DEFAULT_BOILERPLATE_PATTERNS_VI",
    "DEFAULT_VI_STOPWORDS",
    "DEFAULT_PROMPT_TOKEN_OPT_ENABLED",
    "DEFAULT_PROMPT_TOKEN_OPT_MIN_CHUNK_SCORE",
    "DEFAULT_PROMPT_TOKEN_OPT_DEDUPE_JACCARD_THRESHOLD",
    "DEFAULT_PROMPT_TOKEN_OPT_FACTOID_SKIP_HISTORY",
    "DEFAULT_GENERATE_CONTEXT_CHARS_CAP",
    "DEFAULT_REFLECT_ANSWER_PREVIEW_CHARS",
    "DEFAULT_REFLECT_CONTEXT_CHUNK_CAP",
    "DEFAULT_REFLECT_CONTEXT_CHUNK_CHARS",
    "DEFAULT_UNDERSTAND_BOT_CONTEXT_PREVIEW_CHARS",
    "DEFAULT_QUERY_RECEIVED_AUDIT_PREVIEW_CHARS",
    "DEFAULT_CORPUS_VERSION_CACHE_TTL_S",
    "DEFAULT_CORPUS_VERSION_EMPTY_SENTINEL",
    "LEGACY_CORPUS_VERSION_TAG",
    "CACHE_KEY_CORPUS_VERSION_PREFIX",
    "DEFAULT_PIPELINE_PARALLEL_REWRITE_MQ_ENABLED",
    "DEFAULT_PIPELINE_PARALLEL_CACHE_UNDERSTAND_ENABLED",
    "DEFAULT_PIPELINE_PARALLEL_OUTPUT_GUARDS_ENABLED",
    "DEFAULT_PIPELINE_MULTI_QUERY_EMBED_BATCH_ENABLED",
    "DEFAULT_PIPELINE_PRE_RETRIEVAL_PARALLEL_ENABLED",
    "DEFAULT_SKIP_UNDERSTAND_FOR_GREETING",
    "DEFAULT_UNDERSTAND_SKIP_BELOW_TOKENS",
    "DEFAULT_GREETING_PATTERNS",
    "DEFAULT_SINGLE_FLIGHT_MAX_LOCKS",
    # RBAC numeric levels (mirror of shared/rbac.ROLE_LEVELS).
    "DEFAULT_SUPER_ADMIN_LEVEL",
    "DEFAULT_TENANT_ADMIN_LEVEL",
    "DEFAULT_ADMIN_LEVEL",
    "DEFAULT_SERVICE_LEVEL",
    # Notify channel — webhook-driven error alerting.
    "DEFAULT_NOTIFY_CHANNEL_CACHE_TTL_S",
    "DEFAULT_NOTIFY_TIMEOUT_S",
    "DEFAULT_NOTIFY_MAX_RETRIES",
    "DEFAULT_NOTIFY_CONCURRENCY",
    "DEFAULT_NOTIFY_RATE_LIMIT_PER_MIN",
    "DEFAULT_NOTIFY_DEDUP_WINDOW_S",
    "NOTIFY_CHANNEL_CONFIG_KEY",
    "NOTIFY_REDIS_RATE_LIMIT_PREFIX",
    "NOTIFY_REDIS_DEDUP_PREFIX",
    "NOTIFY_MESSAGE_TRUNCATE_CHARS",
    # Webhook HMAC secret rotation (WA-6 — security).
    "DEFAULT_WEBHOOK_HMAC_GRACE_PERIOD_HOURS",
    "DEFAULT_WEBHOOK_HMAC_ALGORITHM",
    "FEATURE_NAME_MAX_LEN",
    "DEFAULT_FEATURE_NAME_UNSET",
    "WORKSPACE_ID_MAX_LEN",
    "WORKSPACE_ID_MIN_LEN",
    "WORKSPACE_ID_PATTERN",
    "WORKSPACE_ID_PATTERN_HUMAN",
    "DEFAULT_WORKSPACE_FALLBACK_MODE",
    "WORKSPACE_SYSTEM_SLUG",
    "DEFAULT_MODEL_TIERS",
    "DEFAULT_TENANT_MODEL_TIER_PROVIDER",
    "DEFAULT_RECOVERY_BATCH_SIZE",
    "DEFAULT_RECOVERY_INTERVAL_S",
    "DEFAULT_RECOVERY_STUCK_THRESHOLD_S",
]

