#!/usr/bin/env python3
"""Load test 30Q from prepared persona file → bot test-spa-id.

Reads 30 VN spa questions from `reports/loadtest_3persona_questions.json`
(generated by 3 in-room Sonnet personas: user-newbie, qaqc-tester, power-user).
Sends each to the bot via test_chat endpoint, saves Q+A pairs + metrics.

Run:
    set -a && source .env && set +a
    .venv/bin/python scripts/loadtest_3persona_consume.py \\
        --questions reports/loadtest_3persona_questions.json \\
        --output reports/LOADTEST_3PERSONA_30Q_<label>_<timestamp>.json
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

import httpx

from ragbot.shared.constants import (
    RAGBOT_LOADTEST_BYPASS_ENV,
    RAGBOT_LOADTEST_BYPASS_HEADER,
)

BASE_URL = os.getenv("RAGBOT_BASE_URL", "http://localhost:3004")
BOT_ID = os.getenv("RAGBOT_TEST_BOT_ID", "test-spa-id")
CHANNEL_TYPE = "web"
WORKSPACE_ID = os.getenv("RAGBOT_TEST_WORKSPACE_ID", "c2f66cb2-9911-5d34-a46e-a4a6da068e23")


def _bypass_headers() -> dict[str, str]:
    """Loadtest-bypass header iff the operator-issued token is in env.

    Empty / unset env returns an empty dict so the harness falls back to
    normal anti-abuse + IP rate-limit behaviour. Setup steps in
    ``docs/dev/LOAD_TEST_RUNBOOK.md``.
    """
    token = os.environ.get(RAGBOT_LOADTEST_BYPASS_ENV, "")
    if not token:
        return {}
    return {RAGBOT_LOADTEST_BYPASS_HEADER: token}


async def get_self_token(client: httpx.AsyncClient) -> str:
    r = await client.get(
        f"{BASE_URL}/api/ragbot/test/tokens/self",
        headers=_bypass_headers(),
    )
    r.raise_for_status()
    return r.json()["token"]


async def ask_bot(
    client: httpx.AsyncClient,
    token: str,
    *,
    connect_id: str,
    question: str,
) -> dict[str, Any]:
    t0 = time.perf_counter()
    body = {
        "bot_id": BOT_ID,
        "channel_type": CHANNEL_TYPE,
        "workspace_id": WORKSPACE_ID,
        "question": question,
        "connect_id": connect_id,
        "bypass_cache": True,
    }
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        **_bypass_headers(),
    }
    try:
        r = await client.post(
            f"{BASE_URL}/api/ragbot/test/chat",
            headers=headers,
            json=body,
            timeout=60,
        )
        r.raise_for_status()
        d = r.json()
        d["latency_ms"] = round((time.perf_counter() - t0) * 1000)
        return d
    except Exception as e:
        return {
            "error": str(e),
            "latency_ms": round((time.perf_counter() - t0) * 1000),
        }


async def run_persona_room(
    client: httpx.AsyncClient,
    token: str,
    persona: str,
    questions: list[str],
    pace_s: float,
) -> list[dict[str, Any]]:
    connect_id = f"loadtest-{persona}-{int(time.time())}"
    out: list[dict[str, Any]] = []

    for i, question in enumerate(questions):
        result = await ask_bot(client, token, connect_id=connect_id, question=question)
        record = {
            "persona": persona,
            "room_connect_id": connect_id,
            "turn_index": i + 1,
            "question": question,
            "answer": result.get("answer", ""),
            "answer_type": result.get("answer_type", ""),
            "answer_reason": result.get("answer_reason", ""),
            "chunks_used": result.get("chunks_used", 0),
            "top_score": result.get("top_score"),
            "tokens": result.get("tokens"),
            "cost_usd": result.get("cost_usd"),
            "latency_ms": result.get("latency_ms"),
            "trace_id": result.get("trace_id"),
            "request_id": result.get("request_id"),
            "error": result.get("error"),
        }
        out.append(record)

        ans_excerpt = (record["answer"] or "")[:80].replace("\n", " ")
        err = record.get("error", "")
        status = "ERR" if err else (record.get("answer_type", "?")[:8])
        print(
            f"  [{persona} #{i+1:02d}] {status:8s} "
            f"score={record['top_score']!s:8s} "
            f"chunks={record['chunks_used']:2d} "
            f"latency={record['latency_ms']:5d}ms "
            f"cost=${record['cost_usd']!s:9s} "
            f"| Q: {question[:45]:<45s} | A: {ans_excerpt[:60]}"
        )
        await asyncio.sleep(pace_s)

    return out


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--questions", required=True, help="Question JSON path")
    ap.add_argument("--output", required=True, help="Output JSON path")
    ap.add_argument("--pace", type=float, default=4.0, help="Sleep between turns (s)")
    ap.add_argument("--label", default="run", help="Label in summary (e.g. baseline, A1.5)")
    args = ap.parse_args()

    qfile = Path(args.questions)
    qdata = json.loads(qfile.read_text(encoding="utf-8"))
    personas = qdata["personas"]

    started_at = datetime.utcnow().isoformat() + "Z"
    started_perf = time.perf_counter()
    all_results: list[dict[str, Any]] = []

    async with httpx.AsyncClient() as client:
        token = await get_self_token(client)
        print(f"[token len={len(token)}] proceed pace={args.pace}s/turn label={args.label}")

        for idx, persona in enumerate(["user-newbie", "qaqc-tester", "power-user"]):
            qs = personas[persona]
            print(f"\n=== Room {idx+1}: {persona} ({len(qs)} questions) ===")
            persona_results = await run_persona_room(client, token, persona, qs, args.pace)
            all_results.extend(persona_results)

    duration_s = round(time.perf_counter() - started_perf, 1)

    n = len(all_results)
    answered = [r for r in all_results if r.get("answer_type") == "answered"]
    refused = [r for r in all_results if r.get("answer_type") in ("refused", "oos", "blocked")]
    errors = [r for r in all_results if r.get("error")]

    latencies = [r["latency_ms"] for r in all_results if r.get("latency_ms") and not r.get("error")]
    latencies.sort()
    p50 = latencies[len(latencies) // 2] if latencies else 0
    p95 = latencies[int(len(latencies) * 0.95)] if latencies else 0
    mean_lat = sum(latencies) / len(latencies) if latencies else 0

    costs = [r["cost_usd"] for r in all_results if r.get("cost_usd") is not None]
    total_cost = sum(costs)
    mean_cost = total_cost / len(costs) if costs else 0

    top_scores = [r["top_score"] for r in all_results if r.get("top_score") is not None]
    mean_score = sum(top_scores) / len(top_scores) if top_scores else 0

    summary = {
        "label": args.label,
        "started_at": started_at,
        "duration_s": duration_s,
        "n_total": n,
        "n_answered": len(answered),
        "n_refused": len(refused),
        "n_errors": len(errors),
        "answer_rate_pct": round(len(answered) / n * 100, 1) if n else 0,
        "refuse_rate_pct": round(len(refused) / n * 100, 1) if n else 0,
        "p50_ms": p50,
        "p95_ms": p95,
        "mean_ms": round(mean_lat),
        "total_cost_usd": round(total_cost, 6),
        "mean_cost_per_turn": round(mean_cost, 6),
        "mean_top_score": round(mean_score, 4),
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        json.dump({"summary": summary, "results": all_results}, f, ensure_ascii=False, indent=2)

    print(f"\n{'='*70}\nSUMMARY ({args.label}):")
    for k, v in summary.items():
        print(f"  {k}: {v}")
    print(f"\nWrote {n} Q+A to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
